import { useEffect,useRef,useState } from 'react';
import {client,configured,universityEmail,sendLogin,checked,readableError} from './api';
export function Icon({name,...props}) {
 const paths={trophy:<><path d="M8 3h8v7a4 4 0 0 1-8 0V3ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v5m-4 2h8m-7-2h6"/></>,upload:<><path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/></>,image:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 1 1 8 0v3m-4 5v2"/></>,check:<path d="m5 12 4 4L19 6"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,leaf:<path d="M20 3C10 2 3 6 3 13a7 7 0 0 0 7 7c7 0 11-7 10-17ZM3 22 15 10"/>};
 return <svg viewBox="0 0 24 24" className="a-icon" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]||paths.leaf}</svg>;
}
export function useAccount() {
 const [user,setUser]=useState(null),[loading,setLoading]=useState(configured);
 useEffect(()=>{if(!client)return;let live=true;client.auth.getUser().then(({data})=>{if(live){setUser(data?.user||null);setLoading(false);}});const {data:{subscription}}=client.auth.onAuthStateChange((_,session)=>{setUser(session?.user||null);setLoading(false);});return()=>{live=false;subscription.unsubscribe();};},[]);
 return {user,loading,valid:Boolean(user?.email_confirmed_at&&universityEmail(user.email||''))};
}
export function Header({admin=false,user,onLogin}) {return <header className="a-header"><a className="a-brand" href="./"><img src="image/nrru-logo.png" alt="ตรามหาวิทยาลัยราชภัฏนครราชสีมา"/><span><b>NRRU <em>Green Campus</em></b><small>มหาวิทยาลัยราชภัฏนครราชสีมา</small></span></a><nav aria-label="เมนูหลัก"><a href="./">แผนที่</a><a href="activity.html" aria-current={!admin?'page':undefined}>กิจกรรม</a>{admin&&<a href="admin.html" aria-current="page">ผู้ดูแล</a>}{user?<button className="a-button secondary compact" onClick={()=>client.auth.signOut()}>ออกจากระบบ</button>:<button className="a-button secondary compact" disabled={!configured} onClick={onLogin}>เข้าสู่ระบบ</button>}</nav></header>;}
export function Modal({title,onClose,children}) {
 const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d.close();document.body.style.overflow=previous;};},[]);
 return <dialog className="a-modal" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="a-modal-header"><h2>{title}</h2><button className="a-close" onClick={onClose} aria-label="ปิด">×</button></div>{children}</dialog>;
}
export function Login({onClose}) {
 const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[until,setUntil]=useState(0),[time,setTime]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setTime(Date.now()),1000);return()=>clearInterval(t);},[]);
 async function request(e){e.preventDefault();setError('');setBusy(true);try{await sendLogin(email);setSent(true);setUntil(Date.now()+60000);}catch(e){setError(readableError(e));}finally{setBusy(false);}}
 async function verify(e){e.preventDefault();setError('');setBusy(true);try{await checked(client.auth.verifyOtp({email:email.trim().toLowerCase(),token:token.trim(),type:'email'}));onClose();}catch(e){setError('รหัสไม่ถูกต้องหรือหมดอายุ กรุณาลองใหม่');}finally{setBusy(false);}}
 return <Modal title="เข้าสู่ระบบด้วยอีเมลมหาวิทยาลัย" onClose={onClose}><div className="a-modal-body"><p className="a-muted">ยืนยันเจ้าของอีเมล @nrru.ac.th เพื่อส่งกิจกรรมและเก็บคะแนน</p><form onSubmit={request}><label>อีเมลมหาวิทยาลัย<input type="email" required value={email} disabled={busy} placeholder="6940108219@nrru.ac.th" onChange={e=>{setEmail(e.target.value);setSent(false);}}/></label><button className="a-button" disabled={busy||time<until}>{busy?'กำลังดำเนินการ…':time<until?`ขอใหม่ได้ใน ${Math.ceil((until-time)/1000)} วินาที`:'ส่งลิงก์เข้าสู่ระบบ'}</button></form>{sent&&<div className="a-notice"><b>ตรวจกล่องอีเมลของคุณ</b><p>เปิดลิงก์ยืนยันที่ส่งไปยัง {email} รวมถึงตรวจโฟลเดอร์สแปม หากอีเมลแสดงรหัสยืนยัน สามารถกรอกด้านล่างได้</p><form onSubmit={verify}><label>รหัสยืนยัน<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,10}" required value={token} onChange={e=>setToken(e.target.value)}/></label><button className="a-button secondary" disabled={busy}>ยืนยันรหัส</button></form></div>}{error&&<p role="alert" className="a-error">{error}</p>}</div></Modal>;
}
export function Status({value}){const text={pending:'รอตรวจ',approved:'ผ่าน · +1 คะแนน',rejected:'ไม่ผ่าน · 0 คะแนน'};return <span className={`a-status ${value}`}>{text[value]||value}</span>;}
export function Footer(){return <footer className="a-footer">NRRU GREEN CAMPUS · แยกขยะให้ถูกประเภท เพื่อพื้นที่ที่น่าอยู่ของทุกคน <a href="admin.html">สำหรับผู้ดูแล</a></footer>;}
