import {useEffect,useRef,useState} from 'react';
import {configured,accountInfo,register,login,logout,readableError} from './api';

export function Icon({name,...props}){
 const paths={trophy:<><path d="M8 3h8v7a4 4 0 0 1-8 0V3ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v5m-4 2h8m-7-2h6"/></>,upload:<><path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/></>,image:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 1 1 8 0v3m-4 5v2"/></>,check:<path d="m5 12 4 4L19 6"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,leaf:<path d="M20 3C10 2 3 6 3 13a7 7 0 0 0 7 7c7 0 11-7 10-17ZM3 22 15 10"/>};
 return <svg viewBox="0 0 24 24" className="a-icon" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]||paths.leaf}</svg>;
}
export function useAccount(){
 const [user,setUser]=useState(null),[loading,setLoading]=useState(configured);
 async function refresh(){if(!configured){setLoading(false);setUser(null);return;}setLoading(true);try{setUser(await accountInfo());}catch{setUser(null);}finally{setLoading(false);}}
 useEffect(()=>{let live=true;const run=async()=>{if(!live)return;await refresh();};run();window.addEventListener('activity-auth-change',run);return()=>{live=false;window.removeEventListener('activity-auth-change',run);};},[]);
 return {user,loading,valid:Boolean(user)};
}
export function Header({admin=false,user,onLogin}){
 async function signOut(){await logout();}
 return <header className="a-header"><a className="a-brand" href="./"><img src="image/nrru-logo.png" alt="ตรามหาวิทยาลัยราชภัฏนครราชสีมา"/><span><b>NRRU <em>Green Campus</em></b><small>มหาวิทยาลัยราชภัฏนครราชสีมา</small></span></a><nav aria-label="เมนูหลัก"><a href="./">แผนที่</a><a href="activity.html" aria-current={!admin?'page':undefined}>กิจกรรม</a>{admin&&<a href="admin.html" aria-current="page">ผู้ดูแล</a>}{user?<><span className="a-muted">{user.student_id}</span><button className="a-button secondary compact" onClick={signOut}>ออกจากระบบ</button></>:<button className="a-button secondary compact" disabled={!configured} onClick={onLogin}>เข้าสู่ระบบ</button>}</nav></header>;
}
export function Modal({title,onClose,children}){
 const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d.close();document.body.style.overflow=previous;};},[]);
 return <dialog className="a-modal" ref={ref} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="a-modal-header"><h2>{title}</h2><button className="a-close" onClick={onClose} aria-label="ปิด">×</button></div>{children}</dialog>;
}
export function Login({onClose}){
 const [mode,setMode]=useState('login'),[studentId,setStudentId]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setError('');if(mode==='register'&&password!==confirm){setError('รหัสผ่านทั้งสองช่องไม่ตรงกัน');return;}setBusy(true);try{if(mode==='register')await register(studentId,password);else await login(studentId,password);onClose();}catch(e){setError(readableError(e));}finally{setBusy(false);}}
 return <Modal title={mode==='register'?'สร้างบัญชีนักศึกษา':'เข้าสู่ระบบ'} onClose={onClose}><div className="a-modal-body"><p className="a-muted">ใช้รหัสนักศึกษา 10 หลักและรหัสผ่านที่คุณตั้งเอง ไม่ต้องใช้อีเมลมหาวิทยาลัย</p><div className="a-actions"><button type="button" className={`a-button ${mode==='login'?'':'secondary'}`} disabled={busy} onClick={()=>{setMode('login');setError('');}}>เข้าสู่ระบบ</button><button type="button" className={`a-button ${mode==='register'?'':'secondary'}`} disabled={busy} onClick={()=>{setMode('register');setError('');}}>สมัครบัญชี</button></div><form onSubmit={submit}><label>รหัสนักศึกษา<input inputMode="numeric" autoComplete="username" pattern="[0-9]{10}" minLength={10} maxLength={10} required value={studentId} disabled={busy} placeholder="6940108219" onChange={e=>setStudentId(e.target.value.replace(/\D/g,'').slice(0,10))}/></label><label>รหัสผ่าน<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} minLength={6} maxLength={72} required value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label>{mode==='register'&&<label>ยืนยันรหัสผ่าน<input type="password" autoComplete="new-password" minLength={6} maxLength={72} required value={confirm} disabled={busy} onChange={e=>setConfirm(e.target.value)}/></label>}<button className="a-button full" disabled={busy}>{busy?'กำลังดำเนินการ…':mode==='register'?'สร้างบัญชี':'เข้าสู่ระบบ'}</button></form>{mode==='register'&&<p className="a-muted">รหัสผ่านจะไม่ถูกเก็บเป็นข้อความปกติ ระบบเก็บเฉพาะค่า hash ในฐานข้อมูล</p>}{error&&<p role="alert" className="a-error">{error}</p>}</div></Modal>;
}
export function Status({value}){const text={pending:'รอตรวจ',approved:'ผ่าน · +1 คะแนน',rejected:'ไม่ผ่าน · 0 คะแนน'};return <span className={`a-status ${value}`}>{text[value]||value}</span>;}
export function Footer(){return <footer className="a-footer">NRRU GREEN CAMPUS · แยกขยะให้ถูกประเภท เพื่อพื้นที่ที่น่าอยู่ของทุกคน <a href="admin.html">สำหรับผู้ดูแล</a></footer>;}
